# Site settings
title: "Saif's Blog"
description: "A blog by Saif Mohammed."
baseurl: ""
url: "https://saifisnotgenius.github.io"

# Build settings
markdown: kramdown
theme: minima

# Permalinks configuration for posts
permalink: /:categories/:year/:month/:day/:title.html
